# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "blog-comments"
client_id = "010bce2ced7d10aebe8ae973e2d3a51a"
application_url = "https://tutorials-water-licensed-origin.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tutorials-water-licensed-origin.trycloudflare.com/auth/callback",
  "https://tutorials-water-licensed-origin.trycloudflare.com/auth/shopify/callback",
  "https://tutorials-water-licensed-origin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "blogs-comment.myshopify.com"
