# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "blog-comments"
client_id = "eb8134c5dc030b352b1a09d775fbcaf2"
application_url = "https://pressure-monte-fastest-algeria.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pressure-monte-fastest-algeria.trycloudflare.com/auth/callback",
  "https://pressure-monte-fastest-algeria.trycloudflare.com/auth/shopify/callback",
  "https://pressure-monte-fastest-algeria.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "blogs-comment.myshopify.com"
